# estoquefacil.yml

openapi: 3.0.0
info:
  title: "Estoque Fácil REST API"
  description: "Uma API REST sobre Controle de Estoque ao BD do Sistema MK-Auth"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Produto:
      type: "object"
      required:
        - "nome"
      properties:
        nome:
          type: "string"
        descricao:
          type: "string"
        grupo:
          type: "string"
        uuid_produto:
          type: "string"
        idforn:
          type: "integer"
        precoatual:
          type: "number"
        precovelho:
          type: "number"
        ultalteracao:
          type: "number"
        peso:
          type: "number"
        ativo:
          type: "string"
        codbarras:
          type: "string"
        med:
          type: "string"
        aplicacao:
          type: "string"
          description: Campo para inserir textos longos ou extensos
        codigo:
          type: "string"

    Item:
      type: "object"
      required:
        - "mac"
      properties:
        mac:
          type: "string"
        obs:
          type: "string"
        valor_compra:
          type: "number"
        fornecedor_id:
          type: "integer"
        produto_id:
          type: "integer"
    
    Movimento:
      type: "object"
      required:
        - "item_id"
        - "user_id"
        - "local_id"
      properties:
        documento:
          type: "string"
        motivo:
          type: "string"
        tipo:
          type: "string"
        obs:
          type: "string"
        contraparte:
          type: "string"
          description: Campo para distinguir se equipamento veio de cliente ou fornecedor
        contraparte_id:
          type: "integer"
          description: Campo para código do cliente ou fornecedor
        item_id:
          type: "integer"
        user_id:
          type: "integer"
        local_id:
          type: "integer"

    User:
      type: "object"
      required:
        - "email"
      properties:
        uuid_acesso:
          type: "string"
        login:
          type: "string"
        email:
          type: "string"

    Cliente:
      type: "object"
      required:
        - "nome"
      properties:
        nome:
          type: "string"

    Fornecedor:
      type: "object"
      required:
        - "razaosoc"
      properties:
        razaosoc:
          type: "string"

  parameters:
    id:
      name: "id"
      description: "Buscar produto pelo id"
      in: path
      required: True
      schema:
        type: "integer"
    
    mac:
      name: "mac"
      description: "Busca Item pelo MAC do equipamento"
      in: path
      required: True
      schema:
        type: "string"
    
    patrimonio:
      name: "patrimonio"
      description: "Busca Item pelo id do patrimônio"
      in: path
      required: True
      schema:
        type: "integer"
    
    id_movimento:
      name: "id"
      description: "Busca movimento pelo id do movimento"
      in: path
      required: True
      schema:
        type: "integer"
    
    idacesso:
      name: "idacesso"
      description: "Buscar user pelo id"
      in: path
      required: True
      schema:
        type: "integer"

    idcliente:
      name: "id"
      description: "Buscar Cliente pelo id"
      in: path
      required: True
      schema:
        type: "integer"

    idfornecedor:
      name: "id"
      description: "Buscar Fornecedor pelo id"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /produtos:
    get:
      operationId: "produtos.read_all"
      tags:
        - "Produtos"
      summary: "Lista os produtos cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
    post:
      operationId: "produtos.create"
      tags:
        - Produtos
      summary: "Insere um novo produto"
      requestBody:
        description: "Cria um novo produto"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "produto"
              $ref: "#/components/schemas/Produto"
      responses:
        "201":
          description: "Produto Cadastrado com sucesso!"

  /produtos/{id}:
    get:
      operationId: "produtos.read_one"
      tags:
        - Produtos
      summary: "Buscar um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Produto encontrado com sucesso"
    
    put:
      tags:
        - Produtos
      operationId: "produtos.update"
      summary: "Alterar um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "produto"
              $ref: "#/components/schemas/Produto"
              
    delete:
      tags:
        - Produtos
      operationId: "produtos.delete"
      summary: "Exclui um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Produto excluído com sucesso!"

  /produtos/{id}/itens:
    get:
      operationId: "produtos.get_itens_by_produto"
      tags:
        - Produtos
      summary: "Buscar os itens de um produto especifico"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Itens para o Produto consultado encontrado com sucesso"  


  /itens:
    get:
      operationId: "itens.read_all"
      tags:
        - Itens
      summary: "Lista os itens cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"

    post:
      operationId: "itens.create"
      tags:
        - Itens
      summary: "Insere um novo item"
      requestBody:
        description: "Cadastra um novo item"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "item"
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: "Item Cadastrado com sucesso!"

  /itens/by-mac/{mac}:
    get:
      operationId: "itens.get_itens_by_mac"
      tags:
        - Itens
      summary: "Buscar um item pelo MAC"
      parameters:
        - $ref: "#/components/parameters/mac"
      responses:
        "200":
          description: "MAC encontrado com sucesso"

  /itens/{patrimonio}:
    get:
      operationId: "itens.read_one"
      tags:
        - Itens
      summary: "Buscar um item cadastrado"
      parameters:
        - $ref: "#/components/parameters/patrimonio"
      responses:
        "200":
          description: "Item encontrado com sucesso"

    put:
      tags:
        - Itens
      operationId: "itens.update"
      summary: "Alterar item cadastrado"
      parameters:
        - $ref: "#/components/parameters/patrimonio"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "item"
              $ref: "#/components/schemas/Item"
  
    delete:
      tags:
        - Itens
      operationId: "itens.delete"
      summary: "Exclui um item"
      parameters:
        - $ref: "#/components/parameters/patrimonio"
      responses:
        "204":
          description: "Item excluído com sucesso!"

  /movimento:
    get:
      operationId: "movimento.read_all"
      tags:
        - "Movimento"
      summary: "Lista a movimentação de itens cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
    post:
      operationId: "movimento.create"
      tags:
        - Movimento
      summary: "Insere uma nova movimentação"
      requestBody:
        description: "Movimento de Entrada ou Saida no sistema"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "movimento"
              $ref: "#/components/schemas/Movimento"
      responses:
        "201":
          description: "Movimento Cadastrado com sucesso!"

  /movimento/{id}:
    get:
      operationId: "movimento.read_one"
      tags:
        - Movimento
      summary: "Lista um movimento de entrada ou saida"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Movimento encontrado!"
  
    put:
      tags:
        - Movimento
      operationId: "movimento.update"
      summary: "Altera um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "movimento"
              $ref: "#/components/schemas/Movimento"
    
    delete:
      tags:
        - Movimento
      operationId: "movimento.delete"
      summary: "Exclui um movimento de entrada ou saida"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Movimento excluído com sucesso!"

  /user:
    get:
      operationId: "user.read_all"
      tags:
        - "User"
      summary: "Lista os usuários cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
  /user/{idacesso}:
    get:
      operationId: "user.read_one"
      tags:
        - User
      summary: "Lista um usuário por id"
      parameters:
        - $ref: "#/components/parameters/idacesso"
      responses:
        "200":
          description: "Usuário encontrado!"

  /cliente:
    get:
      operationId: "cliente.read_all"
      tags:
        - "Cliente"
      summary: "Lista os clientes cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
  /cliente/{id}:
    get:
      operationId: "cliente.read_one"
      tags:
        - Cliente
      summary: "Lista um cliente em específico por id"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Cliente encontrado!"

  /fornecedor:
    get:
      operationId: "fornecedor.read_all"
      tags:
        - "Fornecedor"
      summary: "Lista os Fornecedores cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
  /fornecedor/{id}:
    get:
      operationId: "fornecedor.read_one"
      tags:
        - Fornecedor
      summary: "Lista um fornecedor em específico por id"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Fornecedor encontrado!"