# estoquefacil.yml

openapi: 3.0.0
info:
  title: "Estoque Fácil REST API"
  description: "Uma API REST sobre Controle de Estoque ao BD do Sistema MK-Auth"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Produto:
      type: "object"
      required:
        - "nome"
      properties:
        nome:
          type: "string"
        descricao:
          type: "string"
        grupo:
          type: "string"

    Item:
      type: "object"
      required:
        - "mac"
      properties:
        mac:
          type: "string"
        fonte:
          type: "string"
        volts:
          type: "integer"
        ampere:
          type: "number"
        obs:
          type: "string"
        produto_id:
          type: "integer"
    
    Movimento:
      type: "object"
      required:
        - "item_id"
      properties:
        documento:
          type: "string"
        qtd:
          type: "integer"
        motivo:
          type: "string"
        origem:
          type: "string"
        destino:
          type: "string"
        tipo:
          type: "string"
        obs_movimento:
          type: "string"
        item_id:
          type: "integer"
        user_id:
          type: "integer"

  parameters:
    id:
      name: "id"
      description: "Buscar produto pelo id"
      in: path
      required: True
      schema:
        type: "integer"

    id_patrimonio:
      name: "id_patrimonio"
      description: "Busca Item pelo id do patrimônio"
      in: path
      required: True
      schema:
        type: "integer"
    
    id_movimento:
      name: "id_movimento"
      description: "Busca movimento pelo id do movimento"
      in: path
      required: True
      schema:
        type: "integer"
paths:
  /produtos:
    get:
      operationId: "produtos.read_all"
      tags:
        - "Produtos"
      summary: "Lista os produtos cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
    post:
      operationId: "produtos.create"
      tags:
        - Produtos
      summary: "Insere um novo produto"
      requestBody:
        description: "Cria um novo produto"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "produto"
              $ref: "#/components/schemas/Produto"
      responses:
        "201":
          description: "Produto Cadastrado com sucesso!"

  /produtos/{id}:
    get:
      operationId: "produtos.read_one"
      tags:
        - Produtos
      summary: "Buscar um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Produto encontrado com sucesso"
  /produtos/{id}/edit:
    put:
      tags:
        - Produtos
      operationId: "produtos.update"
      summary: "Alterar um produto"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "produto"
              $ref: "#/components/schemas/Produto"


  /itens:
    get:
      operationId: "itens.read_all"
      tags:
        - Itens
      summary: "Lista os itens cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"

    post:
      operationId: "itens.create"
      tags:
        - Itens
      summary: "Insere um novo item"
      requestBody:
        description: "Cadastra um novo item"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "item"
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: "Item Cadastrado com sucesso!"


  /itens/{id_patrimonio}:
    get:
      operationId: "itens.read_one"
      tags:
        - Itens
      summary: "Buscar um item cadastrado"
      parameters:
        - $ref: "#/components/parameters/id_patrimonio"
      responses:
        "200":
          description: "Item encontrado com sucesso"
  
    put:
      tags:
        - Itens
      operationId: "itens.update"
      summary: "Alterar item cadastrado"
      parameters:
        - $ref: "#/components/parameters/id_patrimonio"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "item"
              $ref: "#/components/schemas/Item"
  
    delete:
      tags:
        - Itens
      operationId: "itens.delete"
      summary: "Exclui um item"
      parameters:
        - $ref: "#/components/parameters/id_patrimonio"
      responses:
        "204":
          description: "Item excluído com sucesso!"

  /movimento:
    get:
      operationId: "movimento.read_all"
      tags:
        - "Movimento"
      summary: "Lista a movimentação de itens cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"
  
    post:
      operationId: "movimento.create"
      tags:
        - Movimento
      summary: "Insere uma nova movimentação"
      requestBody:
        description: "Movimento de Entrada ou Saida no sistema"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "movimento"
              $ref: "#/components/schemas/Movimento"
      responses:
        "201":
          description: "Movimento Cadastrado com sucesso!"

  /movimento/{id_movimento}:
    get:
      operationId: "movimento.read_one"
      tags:
        - Movimento
      summary: "Lista um movimento de entrada ou saida"
      parameters:
        - $ref: "#/components/parameters/id_movimento"
      responses:
        "200":
          description: "Movimento encontrado!"
  
    put:
      tags:
        - Movimento
      operationId: "movimento.update"
      summary: "Altera um produto"
      parameters:
        - $ref: "#/components/parameters/id_movimento"
      responses:
        "200":
          description: "Alteração efetuada com sucesso"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "movimento"
              $ref: "#/components/schemas/Movimento"
    
    delete:
      tags:
        - Movimento
      operationId: "movimento.delete"
      summary: "Exclui um movimento de entrada ou saida"
      parameters:
        - $ref: "#/components/parameters/id_movimento"
      responses:
        "204":
          description: "Movimento excluído com sucesso!"