# estoquefacil.yml

openapi: 3.0.0
info:
  title: "Estoque Fácil REST API"
  description: "Uma API REST sobre Controle de Estoque integrado ao Sistema MK-Auth"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /produtos:
    get:
      operationId: "produtos.produtos.read_all"
      tags:
        - "Produtos"
      summary: "Lê a lista de produtos cadastrados no MK-Auth"
      responses:
        "200":
          description: "Consulta realizada com sucesso!"